### ISSUE TITLE
no such table error

### ISSUE THREAD

**Issue by p31415926** [LakshyaKhatri/Bookshelf-Reader-API#4]
I got below errors while post image 

Request Method: | POST

http://127.0.0.1:8000/api/create-bookshelf/
3.1.5
OperationalError
no such table: detect_spines_bookshelf

**Comment by LakshyaKhatri** [comment]
Did you ran your migrations successfully?

**Comment by p31415926** [comment]
Yes, I successfuly migration it. but i can't find table detect_spines_bookshelf when i try to use sqlites.exe to open db.sqlite3 
only those tables in this file. 

sqlite> .tables
auth_group                  auth_user_user_permissions
auth_group_permissions      django_admin_log
auth_permission             django_content_type
auth_user                   django_migrations
auth_user_groups            django_session
sqlite>

**Comment by LakshyaKhatri** [comment]
The models are defined clearly, I am not understanding why you are facing this issue! (if you could provide the steps to reproduce the issue, I might be able to debug it), or if you are using sqlite, could you try deleting the database files and running the migrations again.

**Comment by p31415926** [comment]
![image](https://user-images.githubusercontent.com/2805478/104724753-124c3200-576c-11eb-8db8-da8f003e27db.png)

**Comment by LakshyaKhatri** [comment]
delete your sqlite db file and run the migrations again.

**Comment by LakshyaKhatri** [comment]
@p31415926, I will push a setup file within few days, so you can delete everything, clone a fresh version, and run that setup file to make everything work.
