### ISSUE TITLE
Missing migrations for detect_spines app?

### ISSUE THREAD

**Issue by mr-nati** [LakshyaKhatri/Bookshelf-Reader-API#6]
Hi, I apologize in advance if I'm doing something silly but I can't seem to run (or find) the migrations for this app. 

Running `makemigrate` and `migrate` only installs migrations for the `admin, auth, contenttypes, sessions` packages but none related to the `detect_spines` app. All of the api calls fail because the database tables don't exist. 

>Internal Server Error: /api/create-bookshelf/
Traceback (most recent call last):
  File "/Users/natitessema/workspace/Bookshelf-Reader-API-master/venv/lib/python3.10/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "/Users/natitessema/workspace/Bookshelf-Reader-API-master/venv/lib/python3.10/site-packages/django/db/backends/sqlite3/base.py", line 477, in execute
    return Database.Cursor.execute(self, query, params)
sqlite3.OperationalError: no such table: detect_spines_bookshelf

Is there a missing `migrations/` directory for the `detect_spines` app or am I doing something wrong? Thanks in advance and thanks for making this project @LakshyaKhatri 🙂

**Comment by LakshyaKhatri** [comment]
Thanks mate! 😄 
I think you are right. It's been a long time since I worked on this project, just checked the code and I couldn't find any migrations either. Did you find a fix though? From what I see, we need to write migrations manually 🤦🏽‍♂️ 
I would love a solution to be proposed ❤️

**Comment by LakshyaKhatri** [comment]
Ah! I see. The models defines the fields in django:
https://github.com/LakshyaKhatri/Bookshelf-Reader-API/blob/master/detect_spines/models.py#L94-L105

In that case, I don't think we need any migrations here
